version: '3.8'

services:
  td-app-test:
    build:
      context: .
      dockerfile: Dockerfile.test

    working_dir: /app
    volumes:
      - ./:/app

    tty: true

    environment:
      DB_URI: postgresql://postgres:postgres@td-db-test:7432/td_test
      REDIS_URI: redis://@redis-test:8379

    env_file:
      - .env

    depends_on:
      - td-db-test

  td-db-test:
    image: postgres:latest
    restart: always
    command: -p 7432 -c fsync=off
    ports:
      - 7432:7432

    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: td_test
