version: '3.8'

services:
  td-app:

    build:
      context: .
      dockerfile: Dockerfile.dev

    working_dir: /app
    volumes:
      - ./:/app

    tty: true

    ports:
      - '8080:8080'
    environment:
      DB_URI: postgresql://postgres:postgres@td-db:6432/todo_db
      REDIS_URI: redis://@td-redis:7379
      PORT: 8080

    env_file:
      - .env

    depends_on:
      - td-db
      - td-redis

  td-db:

    image: postgres:latest
    restart: always
    command: -p 6432
    ports:
      - 6432:6432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db

  td-redis:

    image: redis:latest
    ports:
      - '7379:7379'
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes --port 7379
    restart: always

volumes:
  redis-data:
